package model;
import model.Bill;
import model.BilldetailId;
import model.Stock;

/**
 * Billdetail generated by hbm2java
 */
public class Billdetail implements java.io.Serializable {

	private BilldetailId id;
	private Bill bill;
	private Stock stock;

	public Billdetail() {
	}

	public Billdetail(BilldetailId id, Bill bill, Stock stock) {
		this.id = id;
		this.bill = bill;
		this.stock = stock;
	}

	public BilldetailId getId() {
		return this.id;
	}

	public void setId(BilldetailId id) {
		this.id = id;
	}

	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

}
