package model;
// Generated Oct 6, 2020, 4:08:13 PM by Hibernate Tools 5.4.18.Final

/**
 * BillProductId generated by hbm2java
 */
public class BillProductId implements java.io.Serializable {

	private int idBill;
	private int idProductInfo;

	public BillProductId() {
	}

	public BillProductId(int idBill, int idProductInfo) {
		this.idBill = idBill;
		this.idProductInfo = idProductInfo;
	}

	public int getIdBill() {
		return this.idBill;
	}

	public void setIdBill(int idBill) {
		this.idBill = idBill;
	}

	public int getIdProductInfo() {
		return this.idProductInfo;
	}

	public void setIdProductInfo(int idProductInfo) {
		this.idProductInfo = idProductInfo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BillProductId))
			return false;
		BillProductId castOther = (BillProductId) other;

		return (this.getIdBill() == castOther.getIdBill()) && (this.getIdProductInfo() == castOther.getIdProductInfo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdBill();
		result = 37 * result + this.getIdProductInfo();
		return result;
	}

}
