package model;
// Generated Oct 6, 2020, 4:08:13 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bill generated by hbm2java
 */
public class Bill implements java.io.Serializable {

	private int id;
	private User user;
	private String code;
	private Date createDate;
	private String description;
	private Set billdetails = new HashSet(0);
	private int billStatus;



	public Bill() {
	}

	public Bill(int id, User user, String code, Date createDate) {
		this.id = id;
		this.user = user;
		this.code = code;
		this.createDate = createDate;
	}

	public Bill(int id, User user, String code, Date createDate, String description, Set billdetails) {
		this.id = id;
		this.user = user;
		this.code = code;
		this.createDate = createDate;
		this.description = description;
		this.billdetails = billdetails;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getBilldetails() {
		return this.billdetails;
	}

	public void setBilldetails(Set billdetails) {
		this.billdetails = billdetails;
	}
	public int getBillStatus() {
		return billStatus;
	}

	public void setBillStatus(int billStatus) {
		this.billStatus = billStatus;
	}
}
