package model;
// Generated Oct 6, 2020, 4:08:13 PM by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by hbm2java
 */
public class Branch implements java.io.Serializable {

	private int id;
	private String code;
	private String name;
	private String description;
	private int activeFlag;
	private Set branchCategories = new HashSet(0);

	public Branch() {
	}

	public Branch(int id) {
		this.id = id;
	}

	public Branch(int id, String code, String name, String description, Set branchCategories) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.description = description;
		this.branchCategories = branchCategories;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getBranchCategories() {
		return this.branchCategories;
	}

	public void setBranchCategories(Set branchCategories) {
		this.branchCategories = branchCategories;
	}
	public int getActiveFlag() {
		return activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

}
