package model;
// Generated Oct 6, 2020, 4:08:13 PM by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer id;
	private String name;
	private String measureUnit;
	private Set branchCategories = new HashSet(0);
	private int groupsize;

	public int getGroupsize() {
		return groupsize;
	}

	public void setGroupsize(int groupsize) {
		this.groupsize = groupsize;
	}

	@Override
	public String toString() {
	
		return "id : "+id+" name : "+name+" measureUnit : "+measureUnit ;
	}

	public Category() {
	}

	public Category(String measureUnit) {
		this.measureUnit = measureUnit;
	}

	public Category(String name, String measureUnit, Set branchCategories,int groupsize) {
		this.name = name;
		this.groupsize=groupsize;
		this.measureUnit = measureUnit;
		this.branchCategories = branchCategories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMeasureUnit() {
		return this.measureUnit;
	}

	public void setMeasureUnit(String measureUnit) {
		this.measureUnit = measureUnit;
	}

	public Set getBranchCategories() {
		return this.branchCategories;
	}

	public void setBranchCategories(Set branchCategories) {
		this.branchCategories = branchCategories;
	}

}
