package model;
// Generated Nov 20, 2020, 8:06:33 PM by Hibernate Tools 5.4.18.Final

/**
 * StockId generated by hbm2java
 */
public class Checkstockproperty implements java.io.Serializable {

	private int idStockSize;
	private int idStockColor;
	private int idStockPro;
	private int StockQty;


	public Checkstockproperty() {
	}

	public Checkstockproperty(int idStockSize, int idStockColor, int idStockPro,int StockQty ) {
		this.idStockSize = idStockSize;
		this.idStockColor = idStockColor;
		this.idStockPro = idStockPro;
		this.StockQty=StockQty;
	}

	public int getStockQty() {
		return StockQty;
	}

	public void setStockQty(int stockQty) {
		StockQty = stockQty;
	}
	
	public int getIdStockSize() {
		return this.idStockSize;
	}

	public void setIdStockSize(int idStockSize) {
		this.idStockSize = idStockSize;
	}

	public int getIdStockColor() {
		return this.idStockColor;
	}

	public void setIdStockColor(int idStockColor) {
		this.idStockColor = idStockColor;
	}

	public int getIdStockPro() {
		return this.idStockPro;
	}

	public void setIdStockPro(int idStockPro) {
		this.idStockPro = idStockPro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Checkstockproperty))
			return false;
		Checkstockproperty castOther = (Checkstockproperty) other;

		return (this.getIdStockSize() == castOther.getIdStockSize())
				&& (this.getIdStockColor() == castOther.getIdStockColor())
				&& (this.getIdStockPro() == castOther.getIdStockPro());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdStockSize();
		result = 37 * result + this.getIdStockColor();
		result = 37 * result + this.getIdStockPro();
		return result;
	}

}
