package model;
// Generated Oct 6, 2020, 4:08:13 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductInfo generated by hbm2java
 */
public class ProductInfo implements java.io.Serializable,Cloneable {

	private int id;
	private BranchCategory branchCategory;
	private String name;
	private String description;
	private String code;
	private String imgUrl;
	private long currentPrice;
	private Date createDate;
	private Date updateDate;
	private int activeFlag;
	private Set stocks = new HashSet(0);

	public ProductInfo() {
	}


	public ProductInfo(int id, BranchCategory branchCategory, String name, String code, long currentPrice,
			Date createDate, Date updateDate, int activeFlag) {
		this.id = id;
		this.branchCategory = branchCategory;
		this.name = name;
		this.code = code;
		this.currentPrice = currentPrice;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.activeFlag = activeFlag;
	}

	public ProductInfo(int id, BranchCategory branchCategory, String name, String description, String code,
			String imgUrl, long currentPrice, Date createDate, Date updateDate, int activeFlag, Set stocks)
			 {
		this.id = id;
		this.branchCategory = branchCategory;
		this.name = name;
		this.description = description;
		this.code = code;
		this.imgUrl = imgUrl;
		this.currentPrice = currentPrice;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.activeFlag = activeFlag;
		this.stocks = stocks;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public BranchCategory getBranchCategory() {
		return this.branchCategory;
	}

	public void setBranchCategory(BranchCategory branchCategory) {
		this.branchCategory = branchCategory;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public long getCurrentPrice() {
		return this.currentPrice;
	}

	public void setCurrentPrice(long currentPrice) {
		this.currentPrice = currentPrice;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Set getStocks() {
		return this.stocks;
	}

	public void setStocks(Set stocks) {
		this.stocks = stocks;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return super.clone();
	}
}
