package model;
// Generated Nov 13, 2020, 9:48:28 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private int idrole;
	private String rolename;
	private String roledescription;
	private int activeflag;
	private Date createdate;
	private Date updatedate;
	private Set userRoles = new HashSet(0);

	public Role() {
	}

	public Role(int idrole, String rolename, int activeflag, Date createdate, Date updatedate) {
		this.idrole = idrole;
		this.rolename = rolename;
		this.activeflag = activeflag;
		this.createdate = createdate;
		this.updatedate = updatedate;
	}

	public Role(int idrole, String rolename, String roledescription, int activeflag, Date createdate, Date updatedate,
			Set userRoles) {
		this.idrole = idrole;
		this.rolename = rolename;
		this.roledescription = roledescription;
		this.activeflag = activeflag;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.userRoles = userRoles;
	}

	public int getIdrole() {
		return this.idrole;
	}

	public void setIdrole(int idrole) {
		this.idrole = idrole;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public String getRoledescription() {
		return this.roledescription;
	}

	public void setRoledescription(String roledescription) {
		this.roledescription = roledescription;
	}

	public int getActiveflag() {
		return this.activeflag;
	}

	public void setActiveflag(int activeflag) {
		this.activeflag = activeflag;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

}
