package model;
// Generated Oct 6, 2020, 4:08:13 PM by Hibernate Tools 5.4.18.Final

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private int id;
	private Color color;
	private ProductInfo productInfo;
	private Size size;
	private int quantity;

	public Stock() {
	}

	public Stock(int id, Color color, ProductInfo productInfo, Size size, int quantity) {
		this.id = id;
		this.color = color;
		this.productInfo = productInfo;
		this.size = size;
		this.quantity = quantity;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	public ProductInfo getProductInfo() {
		return this.productInfo;
	}

	public void setProductInfo(ProductInfo productInfo) {
		this.productInfo = productInfo;
	}

	public Size getSize() {
		return this.size;
	}

	public void setSize(Size size) {
		this.size = size;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
