package model;
// Generated Oct 6, 2020, 4:08:13 PM by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {
	private int id;
	private String code;
	private String name;
	private String phone;
	private String gmail;
	private String address;
	private String password;
	private int activeFlag;
	private String gender;
	private Set userWorkingshifts = new HashSet(0);
	private Set bills = new HashSet(0);
	private Set userRoles = new HashSet(0);
	
	

	public User() {
	}

	public User(int id, String code, String name, String phone, String gmail, String address, String password,
			int activeFlag, String gender) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.phone = phone;
		this.gmail = gmail;
		this.address = address;
		this.password = password;
		this.activeFlag = activeFlag;
		this.gender = gender;
	}

	public User(int id, String code, String name, String phone, String gmail, String address, String password,
			int activeFlag, String gender, Set userWorkingshifts, Set bills,Set userRoles) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.phone = phone;
		this.gmail = gmail;
		this.address = address;
		this.password = password;
		this.activeFlag = activeFlag;
		this.gender = gender;
		this.userWorkingshifts = userWorkingshifts;
		this.bills = bills;
		this.userRoles=userRoles;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getGmail() {
		return this.gmail;
	}

	public void setGmail(String gmail) {
		this.gmail = gmail;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Set getUserWorkingshifts() {
		return this.userWorkingshifts;
	}

	public void setUserWorkingshifts(Set userWorkingshifts) {
		this.userWorkingshifts = userWorkingshifts;
	}

	public Set getBills() {
		return this.bills;
	}

	public void setBills(Set bills) {
		this.bills = bills;
	}
	public Set getUserRoles() {
		return userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}
}
