package model;
// Generated Oct 6, 2020, 4:08:13 PM by Hibernate Tools 5.4.18.Final

/**
 * UserWorkingshiftId generated by hbm2java
 */
public class UserWorkingshiftId implements java.io.Serializable {

	private int userId;
	private int workingShiftId;

	public UserWorkingshiftId() {
	}

	public UserWorkingshiftId(int userId, int workingShiftId) {
		this.userId = userId;
		this.workingShiftId = workingShiftId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getWorkingShiftId() {
		return this.workingShiftId;
	}

	public void setWorkingShiftId(int workingShiftId) {
		this.workingShiftId = workingShiftId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserWorkingshiftId))
			return false;
		UserWorkingshiftId castOther = (UserWorkingshiftId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getWorkingShiftId() == castOther.getWorkingShiftId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getWorkingShiftId();
		return result;
	}

}
