package model;
// Generated Oct 6, 2020, 4:08:13 PM by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * WorkingShift generated by hbm2java
 */
public class WorkingShift implements java.io.Serializable {

	private int id;
	private String code;
	private String description;
	private Set userWorkingshifts = new HashSet(0);

	public WorkingShift() {
	}

	public WorkingShift(int id, String code, String description) {
		this.id = id;
		this.code = code;
		this.description = description;
	}

	public WorkingShift(int id, String code, String description, Set userWorkingshifts) {
		this.id = id;
		this.code = code;
		this.description = description;
		this.userWorkingshifts = userWorkingshifts;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getUserWorkingshifts() {
		return this.userWorkingshifts;
	}

	public void setUserWorkingshifts(Set userWorkingshifts) {
		this.userWorkingshifts = userWorkingshifts;
	}

}
