package test;
// Generated Nov 26, 2020, 5:02:29 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bill generated by hbm2java
 */
public class Bill implements java.io.Serializable {

	private Integer idBill;
	private User user;
	private String billCode;
	private Date billCreatedate;
	private String billDescription;
	private Set billdetails = new HashSet(0);

	public Bill() {
	}

	public Bill(User user, String billCode, Date billCreatedate) {
		this.user = user;
		this.billCode = billCode;
		this.billCreatedate = billCreatedate;
	}

	public Bill(User user, String billCode, Date billCreatedate, String billDescription, Set billdetails) {
		this.user = user;
		this.billCode = billCode;
		this.billCreatedate = billCreatedate;
		this.billDescription = billDescription;
		this.billdetails = billdetails;
	}

	public Integer getIdBill() {
		return this.idBill;
	}

	public void setIdBill(Integer idBill) {
		this.idBill = idBill;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getBillCode() {
		return this.billCode;
	}

	public void setBillCode(String billCode) {
		this.billCode = billCode;
	}

	public Date getBillCreatedate() {
		return this.billCreatedate;
	}

	public void setBillCreatedate(Date billCreatedate) {
		this.billCreatedate = billCreatedate;
	}

	public String getBillDescription() {
		return this.billDescription;
	}

	public void setBillDescription(String billDescription) {
		this.billDescription = billDescription;
	}

	public Set getBilldetails() {
		return this.billdetails;
	}

	public void setBilldetails(Set billdetails) {
		this.billdetails = billdetails;
	}

}
