package test;
// Generated Nov 4, 2020, 9:15:15 PM by Hibernate Tools 5.4.18.Final

/**
 * BillProductId generated by hbm2java
 */
public class BillProductId implements java.io.Serializable {

	private int idBiproBill;
	private int idBiproProductinfo;

	public BillProductId() {
	}

	public BillProductId(int idBiproBill, int idBiproProductinfo) {
		this.idBiproBill = idBiproBill;
		this.idBiproProductinfo = idBiproProductinfo;
	}

	public int getIdBiproBill() {
		return this.idBiproBill;
	}

	public void setIdBiproBill(int idBiproBill) {
		this.idBiproBill = idBiproBill;
	}

	public int getIdBiproProductinfo() {
		return this.idBiproProductinfo;
	}

	public void setIdBiproProductinfo(int idBiproProductinfo) {
		this.idBiproProductinfo = idBiproProductinfo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BillProductId))
			return false;
		BillProductId castOther = (BillProductId) other;

		return (this.getIdBiproBill() == castOther.getIdBiproBill())
				&& (this.getIdBiproProductinfo() == castOther.getIdBiproProductinfo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdBiproBill();
		result = 37 * result + this.getIdBiproProductinfo();
		return result;
	}

}
