package test;
// Generated Nov 13, 2020, 9:48:28 PM by Hibernate Tools 5.4.18.Final

/**
 * BillProduct generated by hbm2java
 */
public class BillProduct implements java.io.Serializable {

	private BillProductId id;
	private Bill bill;
	private ProductInfo productInfo;
	private int quantity;
	private int price;

	public BillProduct() {
	}

	public BillProduct(BillProductId id, Bill bill, ProductInfo productInfo, int quantity, int price) {
		this.id = id;
		this.bill = bill;
		this.productInfo = productInfo;
		this.quantity = quantity;
		this.price = price;
	}

	public BillProductId getId() {
		return this.id;
	}

	public void setId(BillProductId id) {
		this.id = id;
	}

	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

	public ProductInfo getProductInfo() {
		return this.productInfo;
	}

	public void setProductInfo(ProductInfo productInfo) {
		this.productInfo = productInfo;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

}
