package test;
// Generated Nov 26, 2020, 5:02:29 PM by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * BranchCategory generated by hbm2java
 */
public class BranchCategory implements java.io.Serializable {

	private int idBracate;
	private Branch branch;
	private Category category;
	private Set productInfos = new HashSet(0);

	public BranchCategory() {
	}

	public BranchCategory(int idBracate, Branch branch, Category category) {
		this.idBracate = idBracate;
		this.branch = branch;
		this.category = category;
	}

	public BranchCategory(int idBracate, Branch branch, Category category, Set productInfos) {
		this.idBracate = idBracate;
		this.branch = branch;
		this.category = category;
		this.productInfos = productInfos;
	}

	public int getIdBracate() {
		return this.idBracate;
	}

	public void setIdBracate(int idBracate) {
		this.idBracate = idBracate;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public Set getProductInfos() {
		return this.productInfos;
	}

	public void setProductInfos(Set productInfos) {
		this.productInfos = productInfos;
	}

}
