package test;
// Generated Nov 13, 2020, 9:48:28 PM by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by hbm2java
 */
public class Branch implements java.io.Serializable {

	private int idBra;
	private String braCode;
	private String braName;
	private String braDescription;
	private Set branchCategories = new HashSet(0);

	public Branch() {
	}

	public Branch(int idBra) {
		this.idBra = idBra;
	}

	public Branch(int idBra, String braCode, String braName, String braDescription, Set branchCategories) {
		this.idBra = idBra;
		this.braCode = braCode;
		this.braName = braName;
		this.braDescription = braDescription;
		this.branchCategories = branchCategories;
	}

	public int getIdBra() {
		return this.idBra;
	}

	public void setIdBra(int idBra) {
		this.idBra = idBra;
	}

	public String getBraCode() {
		return this.braCode;
	}

	public void setBraCode(String braCode) {
		this.braCode = braCode;
	}

	public String getBraName() {
		return this.braName;
	}

	public void setBraName(String braName) {
		this.braName = braName;
	}

	public String getBraDescription() {
		return this.braDescription;
	}

	public void setBraDescription(String braDescription) {
		this.braDescription = braDescription;
	}

	public Set getBranchCategories() {
		return this.branchCategories;
	}

	public void setBranchCategories(Set branchCategories) {
		this.branchCategories = branchCategories;
	}

}
