package test;
// Generated Nov 26, 2020, 5:02:29 PM by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer idCate;
	private String cateName;
	private String cateMeasureunit;
	private String cateCode;
	private Set branchCategories = new HashSet(0);

	public Category() {
	}

	public Category(String cateMeasureunit, String cateCode) {
		this.cateMeasureunit = cateMeasureunit;
		this.cateCode = cateCode;
	}

	public Category(String cateName, String cateMeasureunit, String cateCode, Set branchCategories) {
		this.cateName = cateName;
		this.cateMeasureunit = cateMeasureunit;
		this.cateCode = cateCode;
		this.branchCategories = branchCategories;
	}

	public Integer getIdCate() {
		return this.idCate;
	}

	public void setIdCate(Integer idCate) {
		this.idCate = idCate;
	}

	public String getCateName() {
		return this.cateName;
	}

	public void setCateName(String cateName) {
		this.cateName = cateName;
	}

	public String getCateMeasureunit() {
		return this.cateMeasureunit;
	}

	public void setCateMeasureunit(String cateMeasureunit) {
		this.cateMeasureunit = cateMeasureunit;
	}

	public String getCateCode() {
		return this.cateCode;
	}

	public void setCateCode(String cateCode) {
		this.cateCode = cateCode;
	}

	public Set getBranchCategories() {
		return this.branchCategories;
	}

	public void setBranchCategories(Set branchCategories) {
		this.branchCategories = branchCategories;
	}

}
