package test;
// Generated Nov 13, 2020, 9:48:28 PM by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer idCate;
	private String cateName;
	private String measureUnit;
	private Set branchCategories = new HashSet(0);

	public Category() {
	}

	public Category(String measureUnit) {
		this.measureUnit = measureUnit;
	}

	public Category(String cateName, String measureUnit, Set branchCategories) {
		this.cateName = cateName;
		this.measureUnit = measureUnit;
		this.branchCategories = branchCategories;
	}

	public Integer getIdCate() {
		return this.idCate;
	}

	public void setIdCate(Integer idCate) {
		this.idCate = idCate;
	}

	public String getCateName() {
		return this.cateName;
	}

	public void setCateName(String cateName) {
		this.cateName = cateName;
	}

	public String getMeasureUnit() {
		return this.measureUnit;
	}

	public void setMeasureUnit(String measureUnit) {
		this.measureUnit = measureUnit;
	}

	public Set getBranchCategories() {
		return this.branchCategories;
	}

	public void setBranchCategories(Set branchCategories) {
		this.branchCategories = branchCategories;
	}

}
