package test;
// Generated Nov 4, 2020, 9:15:15 PM by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Color generated by hbm2java
 */
public class Color implements java.io.Serializable {

	private Integer idColor;
	private String colorName;
	private Set stocks = new HashSet(0);

	public Color() {
	}

	public Color(String colorName) {
		this.colorName = colorName;
	}

	public Color(String colorName, Set stocks) {
		this.colorName = colorName;
		this.stocks = stocks;
	}

	public Integer getIdColor() {
		return this.idColor;
	}

	public void setIdColor(Integer idColor) {
		this.idColor = idColor;
	}

	public String getColorName() {
		return this.colorName;
	}

	public void setColorName(String colorName) {
		this.colorName = colorName;
	}

	public Set getStocks() {
		return this.stocks;
	}

	public void setStocks(Set stocks) {
		this.stocks = stocks;
	}

}
