package test;
// Generated Nov 26, 2020, 5:02:29 PM by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Color generated by hbm2java
 */
public class Color implements java.io.Serializable {

	private int idColor;
	private String colorName;
	private Set stocks = new HashSet(0);

	public Color() {
	}

	public Color(int idColor, String colorName) {
		this.idColor = idColor;
		this.colorName = colorName;
	}

	public Color(int idColor, String colorName, Set stocks) {
		this.idColor = idColor;
		this.colorName = colorName;
		this.stocks = stocks;
	}

	public int getIdColor() {
		return this.idColor;
	}

	public void setIdColor(int idColor) {
		this.idColor = idColor;
	}

	public String getColorName() {
		return this.colorName;
	}

	public void setColorName(String colorName) {
		this.colorName = colorName;
	}

	public Set getStocks() {
		return this.stocks;
	}

	public void setStocks(Set stocks) {
		this.stocks = stocks;
	}

}
