package test;
// Generated Nov 4, 2020, 9:15:15 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductInfo generated by hbm2java
 */
public class ProductInfo implements java.io.Serializable {

	private Integer idPro;
	private BranchCategory branchCategory;
	private String proName;
	private String proDescription;
	private String proCode;
	private String proImgUrl;
	private int proCurrentPrice;
	private Date proCreateDate;
	private Date proUpdateDate;
	private int proActiveFlag;
	private Set billProducts = new HashSet(0);
	private Set stocks = new HashSet(0);

	public ProductInfo() {
	}

	public ProductInfo(BranchCategory branchCategory, String proName, String proCode, int proCurrentPrice,
			Date proCreateDate, Date proUpdateDate, int proActiveFlag) {
		this.branchCategory = branchCategory;
		this.proName = proName;
		this.proCode = proCode;
		this.proCurrentPrice = proCurrentPrice;
		this.proCreateDate = proCreateDate;
		this.proUpdateDate = proUpdateDate;
		this.proActiveFlag = proActiveFlag;
	}

	public ProductInfo(BranchCategory branchCategory, String proName, String proDescription, String proCode,
			String proImgUrl, int proCurrentPrice, Date proCreateDate, Date proUpdateDate, int proActiveFlag,
			Set billProducts, Set stocks) {
		this.branchCategory = branchCategory;
		this.proName = proName;
		this.proDescription = proDescription;
		this.proCode = proCode;
		this.proImgUrl = proImgUrl;
		this.proCurrentPrice = proCurrentPrice;
		this.proCreateDate = proCreateDate;
		this.proUpdateDate = proUpdateDate;
		this.proActiveFlag = proActiveFlag;
		this.billProducts = billProducts;
		this.stocks = stocks;
	}

	public Integer getIdPro() {
		return this.idPro;
	}

	public void setIdPro(Integer idPro) {
		this.idPro = idPro;
	}

	public BranchCategory getBranchCategory() {
		return this.branchCategory;
	}

	public void setBranchCategory(BranchCategory branchCategory) {
		this.branchCategory = branchCategory;
	}

	public String getProName() {
		return this.proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public String getProDescription() {
		return this.proDescription;
	}

	public void setProDescription(String proDescription) {
		this.proDescription = proDescription;
	}

	public String getProCode() {
		return this.proCode;
	}

	public void setProCode(String proCode) {
		this.proCode = proCode;
	}

	public String getProImgUrl() {
		return this.proImgUrl;
	}

	public void setProImgUrl(String proImgUrl) {
		this.proImgUrl = proImgUrl;
	}

	public int getProCurrentPrice() {
		return this.proCurrentPrice;
	}

	public void setProCurrentPrice(int proCurrentPrice) {
		this.proCurrentPrice = proCurrentPrice;
	}

	public Date getProCreateDate() {
		return this.proCreateDate;
	}

	public void setProCreateDate(Date proCreateDate) {
		this.proCreateDate = proCreateDate;
	}

	public Date getProUpdateDate() {
		return this.proUpdateDate;
	}

	public void setProUpdateDate(Date proUpdateDate) {
		this.proUpdateDate = proUpdateDate;
	}

	public int getProActiveFlag() {
		return this.proActiveFlag;
	}

	public void setProActiveFlag(int proActiveFlag) {
		this.proActiveFlag = proActiveFlag;
	}

	public Set getBillProducts() {
		return this.billProducts;
	}

	public void setBillProducts(Set billProducts) {
		this.billProducts = billProducts;
	}

	public Set getStocks() {
		return this.stocks;
	}

	public void setStocks(Set stocks) {
		this.stocks = stocks;
	}

}
