package test;
// Generated Nov 26, 2020, 5:02:29 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private int idRole;
	private String roleName;
	private String roleDescription;
	private int roleActiveflag;
	private Date roleCreatedate;
	private Date roleUpdatedate;
	private Set userRoles = new HashSet(0);

	public Role() {
	}

	public Role(int idRole, String roleName, int roleActiveflag, Date roleCreatedate, Date roleUpdatedate) {
		this.idRole = idRole;
		this.roleName = roleName;
		this.roleActiveflag = roleActiveflag;
		this.roleCreatedate = roleCreatedate;
		this.roleUpdatedate = roleUpdatedate;
	}

	public Role(int idRole, String roleName, String roleDescription, int roleActiveflag, Date roleCreatedate,
			Date roleUpdatedate, Set userRoles) {
		this.idRole = idRole;
		this.roleName = roleName;
		this.roleDescription = roleDescription;
		this.roleActiveflag = roleActiveflag;
		this.roleCreatedate = roleCreatedate;
		this.roleUpdatedate = roleUpdatedate;
		this.userRoles = userRoles;
	}

	public int getIdRole() {
		return this.idRole;
	}

	public void setIdRole(int idRole) {
		this.idRole = idRole;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleDescription() {
		return this.roleDescription;
	}

	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

	public int getRoleActiveflag() {
		return this.roleActiveflag;
	}

	public void setRoleActiveflag(int roleActiveflag) {
		this.roleActiveflag = roleActiveflag;
	}

	public Date getRoleCreatedate() {
		return this.roleCreatedate;
	}

	public void setRoleCreatedate(Date roleCreatedate) {
		this.roleCreatedate = roleCreatedate;
	}

	public Date getRoleUpdatedate() {
		return this.roleUpdatedate;
	}

	public void setRoleUpdatedate(Date roleUpdatedate) {
		this.roleUpdatedate = roleUpdatedate;
	}

	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

}
