package test;
// Generated Nov 26, 2020, 5:02:29 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private UserRoleId id;
	private Role role;
	private User user;
	private int usroActiveflag;
	private Date usroCreatedate;
	private Date usroUpdatedate;

	public UserRole() {
	}

	public UserRole(UserRoleId id, Role role, User user, int usroActiveflag, Date usroCreatedate, Date usroUpdatedate) {
		this.id = id;
		this.role = role;
		this.user = user;
		this.usroActiveflag = usroActiveflag;
		this.usroCreatedate = usroCreatedate;
		this.usroUpdatedate = usroUpdatedate;
	}

	public UserRoleId getId() {
		return this.id;
	}

	public void setId(UserRoleId id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getUsroActiveflag() {
		return this.usroActiveflag;
	}

	public void setUsroActiveflag(int usroActiveflag) {
		this.usroActiveflag = usroActiveflag;
	}

	public Date getUsroCreatedate() {
		return this.usroCreatedate;
	}

	public void setUsroCreatedate(Date usroCreatedate) {
		this.usroCreatedate = usroCreatedate;
	}

	public Date getUsroUpdatedate() {
		return this.usroUpdatedate;
	}

	public void setUsroUpdatedate(Date usroUpdatedate) {
		this.usroUpdatedate = usroUpdatedate;
	}

}
