package test;
// Generated Nov 13, 2020, 9:48:28 PM by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private UserRoleId id;
	private Role role;
	private User user;
	private int activeflag;
	private Date createdate;
	private Date updatedate;

	public UserRole() {
	}

	public UserRole(UserRoleId id, Role role, User user, int activeflag, Date createdate, Date updatedate) {
		this.id = id;
		this.role = role;
		this.user = user;
		this.activeflag = activeflag;
		this.createdate = createdate;
		this.updatedate = updatedate;
	}

	public UserRoleId getId() {
		return this.id;
	}

	public void setId(UserRoleId id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getActiveflag() {
		return this.activeflag;
	}

	public void setActiveflag(int activeflag) {
		this.activeflag = activeflag;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

}
