package test;
// Generated Nov 13, 2020, 9:48:28 PM by Hibernate Tools 5.4.18.Final

/**
 * UserWorkingshiftId generated by hbm2java
 */
public class UserWorkingshiftId implements java.io.Serializable {

	private int workingshiftId;
	private int userId;

	public UserWorkingshiftId() {
	}

	public UserWorkingshiftId(int workingshiftId, int userId) {
		this.workingshiftId = workingshiftId;
		this.userId = userId;
	}

	public int getWorkingshiftId() {
		return this.workingshiftId;
	}

	public void setWorkingshiftId(int workingshiftId) {
		this.workingshiftId = workingshiftId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserWorkingshiftId))
			return false;
		UserWorkingshiftId castOther = (UserWorkingshiftId) other;

		return (this.getWorkingshiftId() == castOther.getWorkingshiftId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWorkingshiftId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
