package test;
// Generated Nov 13, 2020, 9:48:28 PM by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * WorkingShift generated by hbm2java
 */
public class WorkingShift implements java.io.Serializable {

	private int idWs;
	private String wsCode;
	private String wsDescription;
	private Set userWorkingshifts = new HashSet(0);

	public WorkingShift() {
	}

	public WorkingShift(int idWs, String wsCode, String wsDescription) {
		this.idWs = idWs;
		this.wsCode = wsCode;
		this.wsDescription = wsDescription;
	}

	public WorkingShift(int idWs, String wsCode, String wsDescription, Set userWorkingshifts) {
		this.idWs = idWs;
		this.wsCode = wsCode;
		this.wsDescription = wsDescription;
		this.userWorkingshifts = userWorkingshifts;
	}

	public int getIdWs() {
		return this.idWs;
	}

	public void setIdWs(int idWs) {
		this.idWs = idWs;
	}

	public String getWsCode() {
		return this.wsCode;
	}

	public void setWsCode(String wsCode) {
		this.wsCode = wsCode;
	}

	public String getWsDescription() {
		return this.wsDescription;
	}

	public void setWsDescription(String wsDescription) {
		this.wsDescription = wsDescription;
	}

	public Set getUserWorkingshifts() {
		return this.userWorkingshifts;
	}

	public void setUserWorkingshifts(Set userWorkingshifts) {
		this.userWorkingshifts = userWorkingshifts;
	}

}
